export const tarifsData = [
  {
    id: 1,
    title: "Beginner",
    text: "Для небольшого исследования",
    icon: "icons/main/tariffs/beginner.svg",
    checkMark: "icons/main/tariffs/check-mark.svg",
    price: "799 ₽",
    priceThrough: "1 200 ₽",
    priceCredit: "или 150 ₽/мес. при рассрочке на 24 мес",
    list: [
      "Безлимитная история запросов",
      "Безопасная сделка",
      "Поддержка 24/7",
    ],
    styles: {
      backgroundColor: "#ffb64f",
      authBorderColor: "2px solid #ffb64f",
    },
    buttonText: "Подробнее",
    authButtonText: "Перейти в личный кабинет",
  },
  {
    id: 2,
    title: "Pro",
    text: "Для HR и фрилансеров",
    icon: "icons/main/tariffs/pro.svg",
    checkMark: "icons/main/tariffs/check-mark.svg",
    price: "1 299 ₽",
    priceThrough: "2 600 ₽",
    priceCredit: "или 279 ₽/мес. при рассрочке на 24 мес",
    list: [
      "Все пункты тарифа Beginner",
      "Экспорт истории",
      "Рекомендации по приоритетам",
    ],
    styles: {
      backgroundColor: "#7ce3e1",
    },
    buttonText: "Подробнее",
  },
  {
    id: 3,
    title: "Business",
    text: "Для корпоративных клиентов",
    icon: "icons/main/tariffs/business.svg",
    checkMark: "icons/main/tariffs/check-mark.svg",
    price: "2 379 ₽",
    priceThrough: "3 700 ₽",
    priceCredit: "или 300 ₽/мес. при рассрочке на 24 мес.",
    list: [
      "Все пункты тарифа Pro",
      "Безлимитное количество запросов",
      "Приоритетная поддержка",
    ],
    styles: {
      backgroundColor: "#000",
    },
    buttonText: "Подробнее",
  },
];
